config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :applications
  resources :users

  post 'appeal_types/create' => 'appeal_types#create'
  put 'appeal_types/update/:id' => 'appeal_types#update'

  post 'decisions/create' => 'decisions#create'
  put 'decisions/update/:id' => 'decisions#update'

  post 'users/create' => 'users#create'

  root 'applications#index'

end

app/models/application.rb
class Application
  include Mongoid::Document
  include Mongoid::Timestamps # adds automagic fields created_at, updated_at

  # field :secretary, type: String  # the author of appeal
  # field :minister, type: String
  field :applicant, type: String
  field :subject, type: String
  field :priority, type: String
  field :contacts, type: String
  field :comments, type: String
  field :status, type: Boolean

  belongs_to :appeal_type, :class_name => 'AppealType', autosave: true
  belongs_to :decision, :class_name => 'Decision', autosave: true

  before_save :strip_whitespace

  def strip_whitespace
    self.applicant = self.applicant.strip if self.applicant
    self.subject = self.subject.strip if self.subject
    self.contacts = self.contacts.strip if self.contacts
    self.comments = self.comments.strip if self.comments
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :authenticate_user!
  before_filter :set_locale

  def set_locale
    I18n.locale = 'ru'
  end

end

app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController
  before_action :set_application, only: [:show, :edit, :update, :destroy]

  # GET /applications
  # GET /applications.json
  def index
    applications = Application.all
    applications = applications.select{|app| app.appeal_type && app.appeal_type.id.to_s == params[:appeal_type] } unless params[:appeal_type].blank?
    applications = applications.select{|app| app.decision && app.decision.id.to_s == params[:decision] } unless params[:decision].blank?
    applications = applications.select{|app| app.priority == params[:priority] } unless params[:priority].blank?
    applications = applications.select{|app|
      date = app.created_at.day.to_s.rjust(2, '00') + "." + app.created_at.month.to_s.rjust(2, '00') + "." + app.created_at.year.to_s
      date >= params[:start]
    } unless params[:start].blank?
    applications = applications.select{|app|
      date = app.created_at.day.to_s.rjust(2, '00') + "." + app.created_at.month.to_s.rjust(2, '00') + "." + app.created_at.year.to_s
      date <= params[:end]
    } unless params[:end].blank?
    unless params[:q].blank?
      query = Regexp.new(".*"+params["q"]+".*")
      applications = applications.select{|app| app.applicant.match(query) || app.subject.match(query) || app.contacts.match(query) }
    end

    @applications = {:new => [], :current => [], :finished => []}
    applications.each{|application|
      if application.status
        @applications[:finished].push(application)
      elsif application.decision
        @applications[:current].push(application)
      else
        @applications[:new].push(application)
      end
    }
    @appeal_types = AppealType.all.map{|t| {'value' => t.id.to_s, 'text' => t.name} }.to_json
    @decisions = Decision.all.map{|t| {'value' => t.id.to_s, 'text' => t.name} }.to_json
  end

  # GET /applications/1
  # GET /applications/1.json
  def show
  end

  # GET /applications/new
  def new
    @application = Application.new
    @appeal_types = AppealType.all
  end

  # GET /applications/1/edit
  def edit
  end

  # POST /applications
  # POST /applications.json
  def create
    @application = Application.new(application_params)

    respond_to do |format|
      if @application.save
        format.html { redirect_to applications_path, notice: 'Обращение было успешно создано.' }
        format.json { render :index, status: :created }
      else
        format.html { render :new }
        format.json { render json: @application.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /applications/1
  # PATCH/PUT /applications/1.json
  def update
    respond_to do |format|
      if @application.update(params[:name] => params[:value])
        format.js
        format.json { render :show, status: :ok, location: @application }
      else
        format.js { render status: :unprocessable_entity }
        format.json { render json: @application.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /applications/1
  # DELETE /applications/1.json
  def destroy
    @application.destroy
    respond_to do |format|
      format.html { redirect_to applications_url, notice: 'Обращение было успешно удалено.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_application
      @application = Application.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def application_params
      params.require(:application).permit(:applicant, :appeal_type, :subject, :contacts, :priority)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/applications_helper.rb
module ApplicationsHelper
end

app/views/applications/_appeal_type_edit.html.haml
%li{'data-id' => "#{appeal_type.id}"}
  %span{ title: 'редактировать', class: 'edit_appeal_type', 'data-name' => 'name', 'data-resource' => 'appeal_type', 'data-type' => 'text', 'data-pk' => "#{appeal_type.id}", 'data-url' => '/appeal_types/update/' + appeal_type.id, 'data-emptytext' => 'укажите название для вида обращения...' }
    = appeal_type.name

:javascript

  $(document).ready(function() {
    $.fn.editable.defaults.mode = 'popup';
    $.fn.editable.defaults.ajaxOptions = {type: "PUT"};

    $('.edit_appeal_type').editable();

  })

app/views/applications/_appeal_type_modal.html.haml
#appeal_type_modal.modal.fade{:role => "dialog", :tabindex => "-1", "aria-hidden" => "true"}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"data-dismiss" => "modal", :type => "button"} &times;
        %h4.modal-title Создание нового вида обращений
      .modal-body
        = bootstrap_form_for :appeal_type, :remote => true, :url => '/appeal_types/create' do |f|
          - if appeal_type.errors.any?
            #error_explanation
              %h2= "#{pluralize(appeal_type.errors.count, "error")} prohibited this application from being saved:"
              %ul
                - appeal_type.errors.full_messages.each do |msg|
                  %li= msg

          .form-group
            = f.text_field :name, :label => "Название", :required => true, :class => 'required'

          .actions
            = f.submit 'Сохранить', :class => 'btn btn-primary btn-sm'

          %hr
            %label Существующие виды обращений
            %ul#appeals_exist
              - appeal_types.each do |appeal_type|
                = render :partial => 'applications/appeal_type_edit', :locals => { :appeal_type => appeal_type }

app/views/applications/_decision_edit.html.haml
%li{'data-id' => "#{decision.id}"}
  %span{ title: 'редактировать', class: 'edit_decision_type', 'data-name' => 'name', 'data-resource' => 'decision', 'data-type' => 'text', 'data-pk' => "#{decision.id}", 'data-url' => '/decisions/update/' + decision.id, 'data-emptytext' => 'укажите название для типового решения...' }
    = decision.name

:javascript

  $(document).ready(function() {
    $.fn.editable.defaults.mode = 'popup';
    $.fn.editable.defaults.ajaxOptions = {type: "PUT"};

    $('.edit_decision_type').editable();

  })

app/views/applications/_decision_modal.html.haml
#decision_modal.modal.fade{:role => "dialog", :tabindex => "-1", "aria-hidden" => "true"}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"data-dismiss" => "modal", :type => "button"} &times;
        %h4.modal-title Создание типового решения
      .modal-body
        = bootstrap_form_for :decision, :remote => true, :url => '/decisions/create' do |f|
          - if decision.errors.any?
            #error_explanation
              %h2= "#{pluralize(decision.errors.count, "error")} prohibited this application from being saved:"
              %ul
                - decision.errors.full_messages.each do |msg|
                  %li= msg

          .form-group
            = f.text_field :name, :label => "Название", :required => true, :class => 'required'

          .actions
            = f.submit 'Сохранить', :class => 'btn btn-primary btn-sm'

          %hr
            %label Существующие типовые решения
            %ul#decisions_exist
              - decisions.each do |decision|
                = render :partial => 'applications/decision_edit', :locals => { :decision => decision }

app/views/applications/_editable_table.html.haml
- if applications.length > 0
  %table.table.table-condensed.col-xs-12.edit_applications
    %thead
      %tr
        %th &nbsp;
        %th.col-xs-2 Время создания
        %th Приоритет
        %th.col-xs-8 Краткое описание
        %th Обработано
        %th
    %tbody
      - priority_colors = {'низкий' => 'green', 'средний' => 'yellow', 'высокий' => 'red'}
      - applications.each_with_index do |application, index|
        %tr.accordion-toggle{"data-target" => "#" + application.id, "data-toggle" => "collapse"}
          %td
            %button.btn.btn-default.btn-xs
              %span.glyphicon.glyphicon-eye-open
          %td= application.created_at
          %td
            %span.glyphicon.glyphicon-flag{:title => application.priority, :style => 'color:' + priority_colors[application.priority] + ';'}
          %td
            %span.applicant
              %b= application.applicant + ": "
            %span.subject
              = application.subject[0..300] + "..."
          %td
            %span.glyphicon.glyphicon-ok{:style => 'opacity:0.3;'}
          %td= button_to 'x', application, :method => :delete, :title => 'удалить', :data => { :confirm => 'Вы уверены, что хотите удалить запись?' }, :style => 'border: none; background: transparent;'
        %tr
          %td.hiddenRow{:colspan => "12"}
            %hr
            .accordion-body.collapse{:id => application.id}
              %b ФИО:
              - if current_user.has_role?(:secretary) || current_user.has_role?(:admin)
                %span{ title: 'редактировать', class: 'edit_param', 'data-name' => 'applicant', 'data-resource' => 'application', 'data-type' => 'text', 'data-pk' => "#{application.id}", 'data-url' => "#{application_path(application)}", 'data-emptytext' => 'укажите ФИО...' }
                  = application.applicant
              - else
                = application.applicant
              %br
              %b Вид обращения
              - if current_user.has_role?(:secretary) || current_user.has_role?(:admin)
                %button.btn.btn-default.btn-xs{:class => 'glyphicon_btn', 'data-toggle' => 'modal', 'data-target' => '#appeal_type_modal', :title => 'Создать новый вид обращений', :type => 'button'}
                  %span.glyphicon.glyphicon-plus
                = ': '
                %span{ title: 'редактировать', class: 'edit_param', 'data-name' => 'appeal_type', 'data-resource' => 'application', 'data-source' => @appeal_types, 'data-type' => 'select', 'data-pk' => "#{application.id}", 'data-url' => "#{application_path(application)}", 'data-emptytext' => 'укажите вид обращения...', 'data-value' => application.appeal_type ? application.appeal_type.id.to_s : "" }
                  = application.appeal_type ? application.appeal_type.name : ""
              - else
                = ': ' + (application.appeal_type ? application.appeal_type.name : "")
              %br
              %b Приоритет:
              %span{ title: 'редактировать', class: 'edit_param', 'data-name' => 'priority', 'data-resource' => 'application', 'data-source' => [{:value => 'низкий', :text => 'низкий'}, {:value => 'средний', :text => 'средний'}, {:value => 'высокий', :text => 'высокий'}].to_json, 'data-type' => 'select', 'data-pk' => "#{application.id}", 'data-url' => "#{application_path(application)}", 'data-emptytext' => 'укажите вид обращения...', 'data-value' => application.priority }
                = application.priority
              %br
              %b Суть обращения:
              %br
              - if current_user.has_role?(:secretary) || current_user.has_role?(:admin)
                %span{ title: 'редактировать', class: 'edit_param', 'data-name' => 'subject', 'data-resource' => 'application', 'data-type' => 'textarea', 'data-pk' => "#{application.id}", 'data-url' => "#{application_path(application)}", 'data-emptytext' => 'укажите суть обращения...' }
                  = application.subject
              - else
                = application.subject
              %br
              %b Контакты для обратной связи:
              %br
              - if current_user.has_role?(:secretary) || current_user.has_role?(:admin)
                %span{ title: 'редактировать', class: 'edit_param', 'data-name' => 'contacts', 'data-resource' => 'application', 'data-type' => 'textarea', 'data-pk' => "#{application.id}", 'data-url' => "#{application_path(application)}", 'data-emptytext' => 'укажите контакты для обратной связи...' }
                  = application.contacts
              - else
                = application.contacts
              %br
              %b Решение
              - if current_user.has_role?(:minister) || current_user.has_role?(:admin)
                %button.btn.btn-default.btn-xs{:class => 'glyphicon_btn', 'data-toggle' => 'modal', 'data-target' => '#decision_modal', :title => 'Создать типовое решение', :type => 'button'}
                  %span.glyphicon.glyphicon-plus
                = ': '
                %span{ title: 'редактировать', class: 'edit_param', 'data-name' => 'decision', 'data-resource' => 'application', 'data-source' => @decisions, 'data-type' => 'select', 'data-pk' => "#{application.id}", 'data-url' => "#{application_path(application)}", 'data-emptytext' => 'примите решение...', 'data-value' => application.decision ? application.decision.id.to_s : "" }
                  = application.decision ? application.decision.name : ""
              - else
                = ': ' + (application.decision ? application.decision.name : "")
              %br
              %b Комментарий:
              - if current_user.has_role?(:minister) || current_user.has_role?(:admin)
                %span{ title: 'редактировать', class: 'edit_param', 'data-name' => 'comments', 'data-resource' => 'application', 'data-type' => 'textarea', 'data-pk' => "#{application.id}", 'data-url' => "#{application_path(application)}", 'data-emptytext' => 'укажите комментарий...' }
                  = application.comments
              - else
                = application.comments
              %br
              %b Выполнено:
              - if current_user.has_role?(:secretary) || current_user.has_role?(:admin)
                %span.edit_status{ 'data-name' => 'status', 'data-url' => "#{application_path(application)}", 'data-pk' => "#{application.id}", 'data-resource' => 'application', 'data-value' => application.status ? 1 : 0 }
              - else
                - if application.status
                  %span.glyphicon.glyphicon-check
                - else
                  %span.glyphicon.glyphicon-unchecked
            %hr

:javascript

  $(document).ready(function() {
    $.fn.editable.defaults.mode = 'inline';
    $.fn.editable.defaults.ajaxOptions = {type: "PUT"};

    $('.edit_param').editable();

    $('.edit_status').editable({
      type: 'checklist',
      source: {'1': 'выполнено' },
      mode: 'popup',
      display: function(value, sourceData) {
        if(value == 0 || (value instanceof Object && $.isEmptyObject(value))) {
          $(this).html('<span class="glyphicon glyphicon-unchecked""></span>');
        } else {
          $(this).html('<span class="glyphicon glyphicon-check"></span>');
        }
      }
    }).on('save', function() {
      $('.accordion-toggle[data-target="#' + $(this).data('pk') + '"] span.glyphicon.glyphicon-ok').css('color', 'green').css('opacity','1');
    });

    $('span[data-name="decision"]').on('save', function() {
      $('.accordion-toggle[data-target="#' + $(this).data('pk') + '"] span.glyphicon.glyphicon-ok').css('color', 'green').css('opacity','1');
    });

    $('span[data-name="priority"]').on('save', function(e, params) {
      $('.accordion-toggle[data-target="#' + $(this).data('pk') + '"] span.glyphicon.glyphicon-flag').css('color', {'низкий': 'green', 'средний': 'yellow', 'высокий': 'red'}[params.newValue]).css('title',params.newValue);
    });

    $('span[data-name="applicant"]').on('save', function(e, params) {
      $('.accordion-toggle[data-target="#' + $(this).data('pk') + '"] span.applicant').html('<b>' + params.newValue + '<b/>');
    });

    $('span[data-name="subject"]').on('save', function(e, params) {
      $('.accordion-toggle[data-target="#' + $(this).data('pk') + '"] span.subject').html(params.newValue.substring(0,300) + "...");
    });
  })

app/views/applications/_form.html.haml
= bootstrap_form_for @application do |f|
  - if @application.errors.any?
    #error_explanation
      %h2= "#{pluralize(@application.errors.count, "error")} prohibited this application from being saved:"
      %ul
        - @application.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.text_field :applicant, :label => "ФИО", :required => true

  .form-group
    %label
      Вид обращения
    = select_tag "application[appeal_type]", options_from_collection_for_select(@appeal_types, "id", "name"), :include_blank => true, :required => true
    %button.btn.btn-primary.btn-xs{:class => 'glyphicon_btn', 'data-toggle' => 'modal', 'data-target' => '#appeal_type_modal', :title => 'Создать новый вид обращений', :type => 'button'}
      %span.glyphicon.glyphicon-plus

  .form-group
    %label
      Приоритет
    = select_tag "application[priority]", "<option selected='selected' value='низкий'>низкий</option><option value='средний'><span class='glyphicon glyphicon-stop' style='color:yellow;'></span> средний</option><option value='высокий'><span class='glyphicon glyphicon-stop' style='color:red;'></span> высокий</option>".html_safe, :required => true

  .form-group
    = f.text_area :subject, :label => "Суть обращения", :required => true

  .form-group
    = f.text_area :contacts, :label => "Контакты для обратной связи", :required => true

  .actions
    = f.submit 'Сохранить', :class => 'btn btn-primary btn-sm'
    = link_to 'Отмена', applications_path, :class => 'btn btn-default btn-sm', :method => :get

= render partial: 'appeal_type_modal', :locals => {:appeal_type => AppealType.new, :appeal_types => @appeal_types}

app/views/applications/_search.html.haml
= form_tag applications_path, :method => :get, :remote => true, :class => 'form-horizontal search' do |f|

  .control-group
    .controls.form-inline
      .input-group
        %span.input-group-addon
          Вид обращения
        = select_tag :appeal_type, options_from_collection_for_select(AppealType.all,"id","name"), :class => 'form-control', :include_blank => true
      .input-group
        %span.input-group-addon
          Решение
        = select_tag :decision, options_from_collection_for_select(Decision.all,"id","name"), :class => 'form-control', :include_blank => true
      .input-group
        %span.input-group-addon
          Приоритет
        = select_tag :priority, options_for_select(["высокий", "средний", "низкий"]), :class => 'form-control', :include_blank => true
      .input-daterange.input-group.col-xs-12.col-md-4
        %span.input-group-addon Период: c
        %input.form-control{:name => "start", :type => "text"}
          %span.input-group-addon по
          %input.form-control{:name => "end", :type => "text"}
      .input-group.col-xs-12.col-md-6
        = text_field_tag :q, '', :class => 'form-control', :placeholder => "Поиск по ключевым словам в полях: ФИО, Суть обращения, Контакты"
      .input-group
        = button_tag(type: 'submit', :class => 'btn btn-primary btn-sm', :id => 'search_btn') do
          Поиск
          %span.glyphicon.glyphicon-search

:javascript

  $(document).ready(function(){
    $('.input-daterange input').datepicker({
      format: 'dd.mm.yyyy',
      todayHighlight: true,
      language: 'ru',
      endDate: '0d',
      autoclose: true
    })
  })

app/views/applications/_search_results.html.haml
.col-xs-2
  %ul.nav.nav-tabs.tabs-left
    %li.active
      %a{:href => "#a", "data-toggle" => "tab"}
        = "Новые (" + applications[:new].length.to_s + ")"
    %li
      %a{:href => "#b", "data-toggle" => "tab"}
        = "В работе (" + applications[:current].length.to_s + ")"
    %li
      %a{:href => "#c", "data-toggle" => "tab"}
        = "Выполненные (" + applications[:finished].length.to_s + ")"
.col-xs-10
  .tab-content
    .tab-pane.active#a
      = render :partial => 'editable_table', :locals => { :applications => applications[:new] }
    .tab-pane#b
      = render :partial => 'editable_table', :locals => { :applications => applications[:current] }
    .tab-pane#c
      = render :partial => 'table', :locals => { :applications => applications[:finished] }

= render partial: 'appeal_type_modal', :locals => {:appeal_type => AppealType.new, :appeal_types => AppealType.all}
= render partial: 'decision_modal', :locals => {:decision => Decision.new, :decisions => Decision.all}

app/views/applications/_table.html.haml
- if applications.length > 0
  %table.table.table-condensed.col-xs-12.edit_applications
    %thead
      %tr
        %th &nbsp;
        %th.col-xs-2 Время создания
        %th.col-xs-8 Краткое описание
    %tbody
      - applications.each_with_index do |application, index|
        %tr.accordion-toggle{"data-target" => "#" + application.id, "data-toggle" => "collapse"}
          %td
            %button.btn.btn-default.btn-xs
              %span.glyphicon.glyphicon-eye-open
          %td= application.created_at
          %td
            %b= application.applicant + ": "
            = application.subject[0..300] + "..."
        %tr
          %td.hiddenRow{:colspan => "12"}
            %hr
            .accordion-body.collapse{:id => application.id}
              %b ФИО:
              = application.applicant
              %br
              %b Вид обращения
              = ': ' + (application.appeal_type ? application.appeal_type.name : "")
              %br
              %b Приоритет:
              = application.priority
              %br
              %b Суть обращения:
              %br
              = application.subject
              %br
              %b Контакты для обратной связи:
              %br
              = application.contacts
              %br
              %b Решение
              = ': ' + (application.decision ? application.decision.name : "")
              %br
              %b Комментарий:
              = application.comments
              %br
              %b Выполнено:
              %span.edit_status{ 'data-name' => 'status', 'data-url' => "#{application_path(application)}", 'data-pk' => "#{application.id}", 'data-resource' => 'application', 'data-value' => application.status ? 1 : 0 }
            %hr

app/views/applications/edit.html.haml
%h1 Editing application

= render 'form'

= link_to 'Show', @application
\|
= link_to 'Back', applications_path

app/views/applications/index.html.haml
= content_for :header do
  Обращения граждан

.col-xs-12.col-md-2
  - if current_user.has_role?(:secretary) || current_user.has_role?(:admin)
    = button_to 'Создать обращение', new_application_path, :class => 'btn btn-primary btn-sm', :method => :get
.col-xs-12.col-md-10
  = render :partial => 'search'

#search_results
  = render :partial => 'search_results', :locals => { applications: @applications }

app/views/applications/index.js.erb
$('#search_results').html('<%= escape_javascript( render partial: 'search_results', :locals => { applications: @applications } ) %>')

app/views/applications/new.html.haml
= content_for :header do
  Создание нового обращения

= render 'form'

app/views/applications/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_application_path(@application)
\|
= link_to 'Back', applications_path