config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :applications
  resources :users

  post 'appeal_types/create' => 'appeal_types#create'
  put 'appeal_types/update/:id' => 'appeal_types#update'

  post 'decisions/create' => 'decisions#create'
  put 'decisions/update/:id' => 'decisions#update'

  post 'users/create' => 'users#create'

  root 'applications#index'

end

app/views/layouts/_navbar.html.haml
%nav.navbar.navbar-default
  / Brand and toggle get grouped for better mobile display
  .navbar-header
    %button.navbar-toggle{"data-target" => "#navbarCollapse", "data-toggle" => "collapse", :type => "button"}
      %span.sr-only Toggle navigation
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    .navbar-brand{:style => 'color: white;'}
      = yield :header
  / Collection of nav links and other content for toggling
  #navbar-main.navbar-collapse.collapse
    -#%ul.nav.navbar-nav
    -#  %li
    -#    %a{:href => "#"} Profile
    -#  %li
    -#    %a{:href => "#"} Messages
    %ul.nav.navbar-nav.navbar-right
      - if current_user
        - if current_user.has_role?(:admin)
          %li.dropdown
            %a.dropdown-toggle{"href" => "#", "data-toggle" => "dropdown"}
              %span.glyphicon.glyphicon-user
              Админ
              %span.caret
            %ul.dropdown-menu{'role' => "menu"}
              %li
                = link_to 'Пользователи', users_path
              %li
                = link_to 'Обращения граждан', root_path
        - elsif current_user.has_role?(:secretary)
          %li
            %a{:style => 'pointer-events:none;'}
              %span.glyphicon.glyphicon-user
              Секретарь
        - elsif current_user.has_role?(:minister)
          %li
            %a{:style => 'pointer-events:none;'}
              %span.glyphicon.glyphicon-user
              Министр
        %li
          = link_to destroy_user_session_path, method: :delete do
            %span.glyphicon.glyphicon-log-out
            Выход

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title
      Приёмная
    = csrf_meta_tags
    = favicon_link_tag 'reception.ico'

  = stylesheet_link_tag "application", :media => "all"
  = javascript_include_tag "application"

  %body
    = render :partial => 'layouts/navbar'
    = yield :top

    .bootstrap_flash
      = bootstrap_flash

    .container-fluid
      .main.row-fluid
        = yield

    .clear

  .afooter.col-sm-12
  .clear